from fpdf import FPDF

class WebsiteDocPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'College Placement Cell - Website Detail Documentation', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(33, 150, 243) # Blue
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 7, text)
        self.ln()

    def add_page_content(self, title, content):
        self.add_page()
        self.chapter_title(title)
        self.chapter_body(content)

pdf = WebsiteDocPDF()

# --- Page 1: Title & Overview ---
pdf.add_page()
pdf.set_y(80)
pdf.set_font('Arial', 'B', 28)
pdf.cell(0, 15, 'WEBSITE DOCUMENTATION', 0, 1, 'C')
pdf.set_font('Arial', 'B', 20)
pdf.cell(0, 15, 'COLLEGE PLACEMENT CELL', 0, 1, 'C')
pdf.set_font('Arial', '', 14)
pdf.ln(20)
pdf.cell(0, 10, 'A complete and detailed guide covering users, architecture, tech stack, and AI', 0, 1, 'C')
pdf.ln(50)
pdf.set_font('Arial', 'I', 12)
pdf.cell(0, 10, 'Generated by Antigravity AI', 0, 1, 'C')

# --- Page 2: Users & Core Features ---
users_content = """This platform serves three primary types of users, each with customized dashboards and privileges aimed at streamlining the entire recruitment lifecycle within the college ecosystem.

1. Students:
- Profile Setup: Students can create detailed profiles, upload their resumes, and add their CGPA and skills.
- Smart Job Discovery: Instead of overwhelming students with all jobs, the system automatically filters and displays only those jobs that match their department and minimum CGPA criteria.
- Application Tracking: Students can track their application statuses seamlessly (e.g., Applied, Shortlisted, Selected).

2. Teachers (Department Coordinators):
- Student Verification: Teachers are responsible for approving and verifying student registrations within their respective departments, ensuring authenticity before a student becomes active.
- Academic Tracking: Teachers monitor student profiles, overall departmental progress, and coordinate with the placement cell.

3. Placement Officers (PCFs):
- Drive Management: PCFs can create job postings, set eligibility criteria (e.g., CS department only, >8.0 CGPA), and manage interviews.
- ATS Evaluation: They can review student applications, assisted by the AI-powered Applicant Tracking System (ATS), to quickly shortlist candidates based on automatic score evaluations.
- Reporting: Generate detailed Excel/PDF reports on placements, applications, and general campus metrics.
"""
pdf.add_page_content("1. User Roles & Capabilities", users_content)

# --- Page 3: Project Structure & Technologies ---
tech_content = """The system is built on a modern decoupled architecture, ensuring scalability, ease of maintenance, and high performance.

Frontend Technologies:
- React.js: The core UI library used for building interactive and dynamic user interfaces.
- Vite: The modern build tool providing incredibly fast hot-module-reloading and optimized production builds.
- Tailwind CSS: A utility-first CSS framework for rapid UI styling, enabling responsive, modern, and clean aesthetic designs.
- React Router: Handles seamless, single-page application (SPA) routing across dashboards.

Backend Technologies:
- Django & Django REST Framework (DRF): The core web framework acting as the robust backend engine. DRF provides a secure and scalable way to expose RESTful APIs.
- SQLite Database: The relational database used to store users, job requests, and application statuses.
- Python: The core backend programming language, enabling complex logic and AI integrations.

Directory Structure:
- client/: The React application holding all UI components, pages, and assets.
- server/: The Django application containing models, views, and APIs.
- server/placement_portal/: Handles robust logic around job drives, posting, and reporting.
- server/student_portal/: Handles student interactions and job applications.
- server/teacher_portal/: Supports verification and tracking features for faculties.
"""
pdf.add_page_content("2. Structure & Technologies", tech_content)

# --- Page 4: APIs & System Interactions ---
api_content = """The application communicates entirely over REST APIs, with secure token-based authentication handling authorization limits.

Key API Categories:

1. Authentication & Profiling (/api/accounts/):
- POST /api/accounts/login/: Exchanges user credentials for encrypted session tokens.
- POST /api/accounts/register/: Initiates registration; directs students to a 'pending approval' state.

2. Student Actions (/api/student/):
- GET /api/student/jobs/eligible/: A smart endpoint that evaluates the logged-in student's DB record (CGPA, Branch), compares it to active Jobs, and returns only valid matches.
- POST /api/student/apply/: Secures the student's application to a specific drive.

3. Teacher Actions (/api/teacher/):
- GET /api/teacher/pending-registrations/: Fetches students awaiting department verification.
- POST /api/teacher/approve/{student_id}/: Updates student request state from pending to active.

4. Placement Officer Actions (/api/placement/):
- POST /api/placement/jobs/: Endpoint dedicated to posting new job drives with complex payloads detailing requirements.
- GET /api/placement/reports/: Calls custom logic to generate data files describing metrics, which are then streamed directly to the frontend.

Workflow Example:
A PCF posts a job via the Placement API. The backend securely saves it. A student hits the Student API to load their dashboard; the backend logic filters out unqualified jobs and returns the new job if relevant. Once applied, status updates trigger the Notification API.
"""
pdf.add_page_content("3. API Architecture & Workflow", api_content)

# --- Page 5: Artificial Intelligence Integration (ATS) ---
ai_content = """The Artificial Intelligence logic applied in this application is the automated Resume parsing and assessing system known as the ATS (Applicant Tracking System). It operates dynamically to accelerate candidate evaluation.

The ATS checker is implemented using strong Natural Language Processing (NLP) techniques with Python:

1. Text Extraction:
Uses libraries like 'pdfminer.six' and 'python-docx' to reliably extract readable text content from standard document formats (PDFs, Word documents).

2. Knowledge Libraries (spaCy NER):
Uses 'spaCy', a state-of-the-art NLP library with its pre-trained english models (`en_core_web_sm`).
- Pre-defined Skills: The system matches extracted resume terms against categorized dictionaries in the system (e.g., Computer Science terms).
- Dynamic Identification: spaCy analyzes parts of speech (Nouns, Adjectives, Proper Nouns) to determine key terms that contextualize a candidate's background outside of standard dictionaries.

3. Machine Learning (TF-IDF):
Uses 'scikit-learn' to execute a Term Frequency-Inverse Document Frequency (TF-IDF) check.
- It vectorizes both the resume text and the job description.
- It then calculates Cosine Similarity to find overall thematic consistency and similarity percentage between the student's history and what the job requires.

4. ATS Scoring Algorithm:
A tailored 0-100% score is formulated:
- 50%: Direct skill match score.
- 30%: Key term overlapping (NLP).
- 20%: TF-IDF Cosine Similarity overlap.
- Missing Sections Penalty: The AI identifies structural flaws (missing 'Education' or 'Contact' sections) and applies light penalties.
"""
pdf.add_page_content("4. AI & Resume Analysis (ATS)", ai_content)

# --- Page 6: Summary & Impact ---
summary_content = """The College Placement Cell project provides an end-to-end organizational overhaul for campus recruitment by intertwining automated filtering with artificial intelligence.

Key Advantages:
- Automation: Replaces a heavily manual process with logic-based triggers, saving time for placement officers.
- Precision: The integration of Smart Eligibility rules out candidate flooding. Companies receive curated lists.
- AI Fairness: Candidates are given an instant ATS match, evaluating them on their objective skill compatibility versus unstructured bias.
- Security: Distinct token authorization prevents students from seeing PCF dashboards, and strict routing limits access logic visually on the front-end.

Conclusion:
By leveraging Vite + React on the frontend and Django REST Framework on the backend, alongside Python-based machine learning modules, this web application delivers a professional, complete solution tailored specifically to the dynamics of academic job placements. 

Generated in April 2026. This documentation is completely comprehensive and tailored for simple but detailed understanding of all architectural systems and users.
"""
pdf.add_page_content("5. Final Summary", summary_content)

pdf.output("/Users/binileb/Athul/college-placement-cell/college_placement_website_details.pdf")
print("PDF Generated Successfully at /Users/binileb/Athul/college-placement-cell/college_placement_website_details.pdf")
