
from fpdf import FPDF

class ProjectReport(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'College Placement Cell - Technical Documentation', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(33, 150, 243) # Blue
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 7, text)
        self.ln()

    def add_page_content(self, title, content):
        self.add_page()
        self.chapter_title(title)
        self.chapter_body(content)

pdf = ProjectReport()

# --- Page 1: Title Page ---
pdf.add_page()
pdf.set_y(80)
pdf.set_font('Arial', 'B', 28)
pdf.cell(0, 15, 'PROJECT DOCUMENTATION', 0, 1, 'C')
pdf.set_font('Arial', 'B', 20)
pdf.cell(0, 15, 'COLLEGE PLACEMENT CELL PORTAL', 0, 1, 'C')
pdf.set_font('Arial', '', 14)
pdf.ln(20)
pdf.cell(0, 10, 'A Complete Technical Overview of Frontend, Backend, and APIs', 0, 1, 'C')
pdf.ln(50)
pdf.set_font('Arial', 'I', 12)
pdf.cell(0, 10, 'Generated by Antigravity AI', 0, 1, 'C')
pdf.cell(0, 10, 'Date: March 15, 2026', 0, 1, 'C')

# --- Page 2: Executive Summary ---
exec_summary = """
The College Placement Cell Portal is a comprehensive web application designed to streamline the recruitment process within an academic institution. It provides a centralized platform for students to find and apply for jobs, teachers to manage student registrations, and placement officers to coordinate with companies and track applications.

Key Highlights:
- Automates the calculating of CGPAs and academic tracking.
- Implements a 'Smart Eligibility' engine where students only see jobs matching their CGPA and department.
- Features an ATS (Applicant Tracking System) utility for resume evaluation.
- Provides real-time notifications and interview scheduling tools.
- Role-based security ensuring distinct dashboards for Students, Teachers, and Officers.
"""
pdf.add_page_content("1. Executive Summary", exec_summary)

# --- Page 3: System Architecture ---
arch = """
The project follows a modern decoupled architecture with a clear separation between the presentation layer and the data management layer.

Backend Architecture:
- Framework: Django & Django REST Framework (DRF).
- Logic: Modular structure with separate apps for Accounts, Student Portal, Teacher Portal, and Placement Portal.
- Authentication: Token-based authentication for secure API access.

Frontend Architecture:
- Framework: React (built with Vite for high performance).
- Styling: Tailwind CSS for a responsive, modern glassmorphic look.
- State Management: React Hooks and Context for efficient data flow.
- Networking: Axios for seamless communication with the backend APIs.
"""
pdf.add_page_content("2. System Architecture", arch)

# --- Page 4: File Usage & Structure ---
files = """
Project Root Directory:
- /client: Contains the React source code, components, and assets.
- /server: Contains the Django project and its various internal apps.

Core Backend Apps:
- accounts/: Manages user creation, authentication, profiles, and notifications.
- student_portal/: Handles student dashboards, job applications, and profile edits.
- teacher_portal/: Handles student approvals, classroom management, and interview selection.
- placement_portal/: Manages job postings, interview scheduling, and export functionalities.

Core Frontend Structure:
- src/pages/: The main views (Home, Student Dashboard, PCF Dashboard, etc.).
- src/components/: Reusable UI elements (Navigation, Cards, Forms).
- src/router/: Centralized routing logic using React Router DOM.
"""
pdf.add_page_content("3. File Usage & Project Structure", files)

# --- Page 5: Backend Details - Models & Connections ---
models_text = """
The system uses a relational database schema centered around a custom User model.

Primary Models:
- User: Custom authentication model using phone numbers and roles.
- Student: Stores personal data, CGPA, backlogs, and ATS scores. Linked 1-to-1 with User.
- Teacher & PlacementOfficer: Profile extensions for specific roles.
- Job: Stores job details including eligibility (min CGPA, allowed departments).
- JobApplication: Tracks the status of student applications (Applied, Shortlisted, Selected).
- Notification: Persistent alerts sent to users regarding job updates or approvals.
- RegistrationRequest: Temporary storage for new signups awaiting teacher verification.
- Interview: Manages scheduling and meeting links for company drives.
"""
pdf.add_page_content("4. Backend: Models & Database Connections", models_text)

# --- Page 6: Backend Details - Functions & Logic ---
logic_text = """
Key Backend Functions and Logic:
- calculate_cgpa() inside Student model: Automatically computes overall CGPA whenever a SemesterResult is saved, weighted by credits.
- update_profile_completion(): Dynamically tracks how much of a student's profile is filled.
- RegisterView: Multi-step registration logic that creates a RegistrationRequest instead of a direct User for students.
- Job Filtering Logic: Located in StudentDashboardView, this filters jobs based on the student's department, CGPA, and backlog count.
- PDF Export Logic: Custom views that generate on-the-fly PDF reports for student lists and application statuses using the server-side PDF engine.
- ATS Parsing: Located in ats_utils.py, it uses NLP patterns to score student resumes against job requirements.
"""
pdf.add_page_content("5. Backend: Core Functions & Business Logic", logic_text)

# --- Page 7: API Documentation ---
api_text = """
The system exposes a RESTful API for frontend consumption.

Accounts API:
- POST /api/accounts/login/: User authentication and token retrieval.
- POST /api/accounts/register/: Initial signup for all roles.
- GET /api/accounts/notifications/: Fetching user-specific alerts.

Student API:
- GET /api/student/dashboard/: Retrieve eligible jobs for the logged-in student.
- POST /api/student/apply/: Submit a job application.
- GET /api/student/profile/: Retrieve and update student-specific data.

Teacher/Placement API:
- GET /api/teacher/registrations/pending/: View students awaiting approval.
- POST /api/placement/jobs/: Create and manage new recruitment drives.
- GET /api/placement/applications/export/: Download application reports in PDF format.
"""
pdf.add_page_content("6. API Endpoints & Communication", api_text)

# --- Page 8: Frontend: Pages & UI Flow ---
frontend_pages = """
The user interface is built to be intuitive and role-specific.

Pages:
- Home / Index: Information about the placement cell and recent updates.
- Student Dashboard: A grid view of 'Eligible Jobs' based on the backend filtering logic.
- Placement Officer Dashboard: High-level metrics showing total applications, students, and active drives.
- Teacher Dashboard: Focuses on administrative tasks like approving new students and viewing departmental performance.
- Profile Page: A comprehensive form for users to manage their details and for students to upload resumes for ATS analysis.

UI Features:
- Responsive Design: Fully compatible with mobile and desktop.
- Interactivity: Uses Framer Motion for smooth transitions and hover effects.
- Real-time Updates: Toast notifications for feedback on actions like successful job application.
"""
pdf.add_page_content("7. Frontend: Pages & User Experience", frontend_pages)

# --- Page 8 (Continued): Specialized Systems ---
special_systems = """
Advanced Modules:
1. ATS (Applicant Tracking System):
   - Scans resumes (PDF/Docx).
   - Extracts skills and provides a score.
   - Highlights 'missing skills' based on the job description.

2. Smart Notification System:
   - Notifies students when their application status changes.
   - Notifies teachers about new registration requests.
   - Persistent storage allows users to see history.

3. Automated Eligibility:
   - Prevents students from applying if they don't meet the CGPA criteria.
   - Restricts applications based on the 'Allowed Departments' field in the Job model.
"""
pdf.add_page_content("8. Specialized Modules & Systems", special_systems)

# --- Page 9: Connection & System Workflow ---
workflow = """
How the system connects all components (Lifecycle of an Application):

1. Onboarding: A student registers. A RegistrationRequest is created in the DB.
2. Verification: A Teacher/PCF reviews the request on their dashboard and clicks 'Approve'. This triggers the creation of a User and a Student profile.
3. Job Posting: The Placement Officer posts a new Job with a Min CGPA of 8.0 for the CS department.
4. Visibility: A student from Civil Engineering or a student with 7.5 CGPA will NOT see this job on their dashboard. A qualified student sees it and clicks 'Apply'.
5. Processing: The application moves to 'Under Review'. The PCF officer reviews the resume (evaluated by the ATS engine).
6. Shortlisting: The officer updates the status to 'Shortlisted'. A notification is instantly sent to the student.
7. Interview: An Interview is scheduled via the Interview model, and the meeting link is shared with the student.
"""
pdf.add_page_content("9. System Connection & Workflow", workflow)

# --- Page 10: Conclusion & Future Enhancements ---
conclusion = """
The College Placement Cell Portal successfully digitizes and automates a previously manual and error-prone process. By integrating academic tracking with recruitment, it ensures that candidates are fairly evaluated based on their performance and skills.

Future Roadmap:
- Real-time Chat: Integrated messaging between students and recruiters.
- Al-Mock Interviews: Native video conferencing with AI feedback.
- Analytics Dashboard: Graphical representation of placement trends over the years.
- Mobile App: Native Android/iOS applications for on-the-go notifications.

This documentation serves as a complete guide to the current system state as of March 2026.
"""
pdf.add_page_content("10. Conclusion & Future Roadmap", conclusion)

pdf.output("/Users/binileb/Athul/college-placement-cell/College_Placement_Cell_Documentation.pdf")
print("PDF Generated Successfully at /Users/binileb/Athul/college-placement-cell/College_Placement_Cell_Documentation.pdf")
