# Generated by Django 6.0.2 on 2026-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_job_student_overall_cgpa_student_profile_completion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='student', max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
