# Generated by Django 6.0.2 on 2026-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registration_requests/'),
        ),
    ]
