# Generated by Django 6.0.2 on 2026-03-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_job_qualification_job_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
