# Generated by Django 6.0.2 on 2026-03-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ats_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('meeting_link', models.URLField(max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('selected_students', models.ManyToManyField(blank=True, related_name='interviews', to='accounts.student')),
            ],
        ),
    ]
