# Generated by Django 6.0.2 on 2026-03-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student_ats_score_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posters/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_posters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
