# Generated by Django 6.0.2 on 2026-03-10 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driveposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveposter',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_posters', to=settings.AUTH_USER_MODEL),
        ),
    ]
